<?xml version="1.0" encoding="utf-8"?><Database Name="AtticagoldDB" Class="BranchDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=AGC003-PC\SQLEXPRESS;Initial Catalog=AtticagoldDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AtticagoldDB" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblBranches" Member="tblBranches">
    <Type Name="tblBranch">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="branch_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="branch_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="branch_manager_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mobile_number" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="alter_mobile_number" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="createdat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deletedat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>